# Generated by Django 4.1.7 on 2023-03-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='longitude',
            new_name='lon',
        ),
    ]
